---
- hosts: all
  tasks:
    - name: "Make sure directories exist"
      file:
        path: /{{ item.path }}
        state: directory
        mode: 0775
      with_filetree: ood_root/
      when: item.state == "directory"

    - name: OOD configuration files
      template:
        src: "{{ item.src }}"
        path: /etc/{{ item.path | regex_replace('\.j2$','') }}
        mode: "{{ item.mode }}"
      with_filetree: ood_root/etc/
      when: item.state == "file"

    - name: "Symlink Cluster yml"
      file: 
        src: /etc/ood/config/clusters.d/Cluster.yml
        path: /etc/ood/config/clusters.d/{{ inventory_hostname|title  }}.yml
        state: link

    - name: "Dashboard shell tweak"
      template:
        src: "ood_root/var/www/ood/apps/sys/shell/manifest.yml.j2"
        path: "/var/www/ood/apps/sys/shell/manifest.yml"

    - name: "Dashboard Branding"
      copy:
        src: "{{ item }}"
        path: "/var/www/ood/public/"
      with_fileglob: 
         - "ood_root/var/www/ood/public/*"

    - name: "Deploy OOD Apache config"
      command: "/opt/ood/ood-portal-generator/sbin/update_ood_portal"
      register: update_ood_portal_out
      failed_when: update_ood_portal_out.rc > 1 

    - name: "Restart httpd"
      when: update_ood_portal_out.rc == 0
      systemd:
        name: "{{ item }}"
        state: reloaded
      with_items:
        - "httpd24-httpd"
        - "httpd24-htcacheclean"
